### ISSUE TITLE
Problems with example

### ISSUE THREAD

**Issue by gtuxyco** [VinniaAB/shipping#5]
Ok, after you change i try and give me other error.

> ( ! ) Fatal error: Uncaught TypeError: Argument 1 passed to Vinnia\Shipping\DHL\Service::getQuotes() must be an instance of Vinnia\Shipping\QuoteRequest, instance of Vinnia\Shipping\Address given, called in C:\wamp64\www\test\test.php on line 81 and defined in C:\wamp64\www\test\vendor\vinnia\shipping\src\DHL\Service.php on line 194

> ( ! ) TypeError: Argument 1 passed to Vinnia\Shipping\DHL\Service::getQuotes() must be an instance of Vinnia\Shipping\QuoteRequest, instance of Vinnia\Shipping\Address given, called in C:\wamp64\www\test\test.php on line 81 in C:\wamp64\www\test\vendor\vinnia\shipping\src\DHL\Service.php on line 194

--
then i change the example trying to pass a QueoteRequest object 

```
use Vinnia\Shipping\DHL\Credentials as DHLCredentials;
use Vinnia\Shipping\DHL\Service as DHLService;
use Vinnia\Shipping\Address;
use Vinnia\Shipping\Parcel;
use Vinnia\Util\Measurement\Amount;
use Vinnia\Util\Measurement\Unit;
use Vinnia\Shipping\QuoteRequest;


$guzzle = new \GuzzleHttp\Client();
$credentials = new DHLCredentials('site_id', 'password', 'account_number');
$dhl = new DHLService($guzzle, $credentials);

$sender = new Address('', [], '97334', 'Luleå', '', 'SE');
$recipient = new Address('', [], '21115', 'Malmö', '', 'SE');
$parcel = Parcel::make(30, 30, 30, 5, Unit::CENTIMETER, Unit::KILOGRAM);
$request = new QuoteRequest ($sender, $recipient, $parcel );

$dhl->getQuotes($request)->then(function (array $quotes) {
    // do something with the quote array
    
    foreach ($quotes as $quote) {
        echo $quote->getProduct() . PHP_EOL;
    }
}); 

```
then give me this error 

> ( ! ) Fatal error: Uncaught TypeError: Argument 3 passed to Vinnia\Shipping\QuoteRequest::__construct() must be of the type array, object given, called in C:\wamp64\www\test\test.php on line 56 and defined in C:\wamp64\www\test\vendor\vinnia\shipping\src\QuoteRequest.php on line 109

> ( ! ) TypeError: Argument 3 passed to Vinnia\Shipping\QuoteRequest::__construct() must be of the type array, object given, called in C:\wamp64\www\test\test.php on line 56 in C:\wamp64\www\test\vendor\vinnia\shipping\src\QuoteRequest.php on line 109

i go further and edit QuoteRequest.php line 109 to:
`  public function __construct(Address $sender, Address $recipient, Parcel $parcels)
`

and still errors

> ( ! ) Fatal error: Uncaught TypeError: array_keys() expects parameter 1 to be array, object given in C:\wamp64\www\test\vendor\vinnia\shipping\src\DHL\Service.php on line 109

> ( ! ) TypeError: array_keys() expects parameter 1 to be array, object given in C:\wamp64\www\test\vendor\vinnia\shipping\src\DHL\Service.php on line 109

i edit DHL\Service.php line 109 to
`        }, $request->parcels, array_keys(get_object_vars($request->parcels)));
`
and this error

> ( ! ) Warning: array_map(): Expected parameter 2 to be an array, object given in C:\wamp64\www\test\vendor\vinnia\shipping\src\DHL\Service.php on line 109

--
So, i know i'm doing wrong, can you help me a little bit to make work properly?

Thanks for contribute the community with your work, its very appreciate.

**Comment by gtuxyco** [comment]
Ok, this apparently work but give me a blank page.
```
use Vinnia\Shipping\DHL\Credentials as DHLCredentials;
use Vinnia\Shipping\DHL\Service as DHLService;
use Vinnia\Shipping\Address;
use Vinnia\Shipping\Parcel;
use Vinnia\Util\Measurement\Amount;
use Vinnia\Util\Measurement\Unit;
use Vinnia\Shipping\QuoteRequest;

$guzzle = new \GuzzleHttp\Client();
$credentials = new DHLCredentials('site_id', 'password', 'account_number');
$dhl = new DHLService($guzzle, $credentials);

$sender = new Address('', [], '97334', 'Luleå', '', 'SE');
$recipient = new Address('', [], '21115', 'Malmö', '', 'SE');
$parcel = [Parcel::make(30, 30, 30, 5, Unit::CENTIMETER, Unit::KILOGRAM)];
$request = new QuoteRequest ($sender, $recipient, $parcel );

$dhl->getQuotes($request)->then(function (array $quotes) {
    // do something with the quote array
    
    foreach ($quotes as $quote) {
        echo $quote->getProduct() . PHP_EOL;
    }
});

```

**Comment by gtuxyco** [comment]
```
use Vinnia\Shipping\DHL\Credentials as DHLCredentials;
use Vinnia\Shipping\DHL\Service as DHLService;
use Vinnia\Shipping\Address;
use Vinnia\Shipping\Parcel;
use Vinnia\Util\Measurement\Amount;
use Vinnia\Util\Measurement\Unit;
use Vinnia\Shipping\QuoteRequest;

$guzzle = new \GuzzleHttp\Client();
$credentials = new DHLCredentials('site_id', 'password', 'account_number');
$dhl = new DHLService($guzzle, $credentials);

$sender = new Address('', [], '97334', 'Luleå', '', 'SE');
$recipient = new Address('', [], '21115', 'Malmö', '', 'SE');
$parcel = [Parcel::make(30, 30, 30, 5, Unit::CENTIMETER, Unit::KILOGRAM)];
$request = new QuoteRequest ($sender, $recipient, $parcel );
$promise = $dhl->getQuotes($request);
$quotes = $promise->wait();
foreach ($quotes as $quote) {
    var_dump ($quote);
}
```

I try with this, and get this error.

> Fatal error: Uncaught Vinnia\Shipping\ServiceException in  test/vendor/vinnia/shipping/src/DHL/Service.php:603 Stack trace: #0  test/vendor/vinnia/shipping/src/DHL/Service.php(203): Vinnia\Shipping\DHL\Service->throwError('<?xml version="...') #1  test/vendor/guzzlehttp/promises/src/Promise.php(203): Vinnia\Shipping\DHL\Service->Vinnia\Shipping\DHL\{closure}(Object(GuzzleHttp\Psr7\Response)) #2  test/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3  test/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4  test/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(98): GuzzleHttp\Promise\TaskQueue->run() #5 /var/ww in  test/vendor/vinnia/shipping/src/DHL/Service.php on line 603
